### ISSUE TITLE
로그인을 계속 해야하는 문제

### ISSUE THREAD

**Issue by wonyongChoi05** [BSSM-BGIT/BGIT-Frontend#4]
서버에서 jwt 발급 방식 변경 후 **액세스 토큰 만료 시간마다 계속 로그인** 해줘야하는 이슈가 생겼습니다.
리프레스 토큰을 통해 액세스 토큰 자동 재발급을 해줘야할 것 같습니다. @leehj050211

**Comment by leehj050211** [comment]
프론트에서는 이미 리프레시 토큰으로 자동 재발급 받고 있습니다.
제가 직접 확인해보니 토큰을 재발급 받을 때 백엔드에서 토큰이 만료되었다고 나오며, 처음 로그인시 토큰을 발급받을 때 백엔드에서 액세스 토큰과 리프레시 토큰의 만료날짜를 동일하게 설정해서 주는 것을 확인했습니다.
그동안 토큰 자동 재발급이 잘 작동하고 있었고 백엔드 업데이트 후 이러는 것을 보아 백엔드 쪽 문제인 것 같습니다. @wonyongChoi05

**Comment by wonyongChoi05** [comment]
쿠키 유효시간이 int 타입인데 원래 사용하던 jwt 타입이 long타입이라 int 타입 최댓값을 초과해서 리프레시토큰이 -값이 되어서 발생한 이슈같습니다. 수정해서 재배포했습니다. @leehj050211

**Comment by wonyongChoi05** [comment]
토큰 이슈 진짜 해결했습니다. 확인부탁드립니다. 😭 @leehj050211
